### ISSUE TITLE
upgrade.php error table ticket_nachricht

### ISSUE THREAD

**Issue by Diralytic** [OpenXE-org/OpenXE#90]
Hallo!

Wenn ich im Terminal "php data/upgrade.php -db -do" ausführe bekomme ich folgenden Fehler.
Dies ist der einzige Upgrade Step der nicht funktioniert. Habe die mit einer Abfrage übersprungen.

```
Upgrade step 5 of ... ALTER TABLE `ticket_nachricht` ADD  KEY `FullText` (`betreff`,`verfasser`,`text`);

PHP Fatal error:  Uncaught mysqli_sql_exception: Specified key was too long; max key length is 3072 bytes in /var/www/html/OpenXE/upgrade/data/upgrade.php:
```

OpenXE V1.10
Ubuntu 22.04
Apache v2.4.52
PHP v8.1.2
10.6.12-MariaDB
InnoDB utf8mb3_general_ci

Vielen Dank!

**Comment by OpenXE-ERP** [comment]
Kannst Du mal bitte das Upgrade zusätzlich mit der Option "-v" ausführen und das Ergebnis hier einstellen?

Ist das eine migrierte Datenbank mit Ticket-Inhalten in der Tabelle ticket_nachricht?

**Comment by Diralytic** [comment]
Ja dies ist eine Datenbank von Xentral.
Die Version habe ich leider nicht herausgefunden, aber dürfte die aktuellste sein.

Hier ist der Output:

```
--------------- OpenXE upgrade ---------------
--------------- 2023-08-02 18:35:20 ---------------
--------------- Loading from database 'xentral@localhost'... ---------------
--------------- Loading from JSON... ---------------
Table count database 595 vs. JSON 595
--------------- Comparing JSON 'openxe@localhost' vs. database 'xentral@localhost' ---------------
type => [Key existence], table => [abrechnungsartikel], in DB => [artikel]
type => [Key existence], table => [adresse], in DB => [vertrieb]
type => [Key existence], table => [adresse], in DB => [innendienst]
type => [Key existence], table => [adresse], in DB => [sponsor]
type => [Key existence], table => [adresse], in DB => [typ]
type => [Column existence], table => [adresse_accounts], in DB => [email]
type => [Column existence], table => [adresse_accounts], in DB => [notiz]
type => [Key existence], table => [angebot], in DB => [gruppe]
type => [Key existence], table => [angebot], in DB => [usereditid]
type => [Key existence], table => [artikel], in DB => [usereditid]
type => [Key existence], table => [auftrag], in DB => [gruppe]
type => [Key existence], table => [auftrag], in DB => [usereditid]
type => [Key existence], table => [bestellung], in DB => [usereditid]
type => [Key existence], table => [gutschrift], in DB => [gruppe]
type => [Key existence], table => [gutschrift], in DB => [usereditid]
type => [Key existence], table => [lieferschein], in DB => [vertriebid]
type => [Key existence], table => [lieferschein], in DB => [usereditid]
type => [Key existence], table => [rechnung], in DB => [vertriebid]
type => [Key existence], table => [rechnung], in DB => [gruppe]
type => [Key existence], table => [rechnung], in DB => [usereditid]
type => [Key existence], table => [shopexport_artikel], in DB => [artikel]
type => [Column existence], table => [shopexport_zahlweisen], in DB => [updated]
type => [Key existence], table => [verkaufszahlen_chart_projekt], in DB => [projekt]
type => [Key existence], table => [versand], in DB => [adresse]
24 differences.
--------------- Comparing database 'xentral@localhost' vs. JSON 'openxe@localhost' ---------------
type => [Key definition], table => [supersearch_index_item], key => [FullText], property => [Index_type], in JSON => [FULLTEXT], in DB => [BTREE]
type => [Key existence], table => [ticket_nachricht], in JSON => [FullText]
2 differences.
--------------- Calculating database upgrade for 'xentral@localhost'... ---------------
SET SQL_MODE='ALLOW_INVALID_DATES';
SET SESSION innodb_strict_mode=OFF;
ALTER TABLE 'supersearch_index_item' DROP KEY 'FullText';
ALTER TABLE 'supersearch_index_item' ADD  KEY 'FullText' ('search_words');
ALTER TABLE 'ticket_nachricht' ADD  KEY 'FullText' ('betreff','verfasser','text');
5 upgrade statements
--------------- Executing database upgrade for 'xentral@localhost' database... ---------------
Upgrade step 1 of 5... 
SET SQL_MODE='ALLOW_INVALID_DATES';
Upgrade step 2 of 5... 
SET SESSION innodb_strict_mode=OFF;
Upgrade step 3 of 5... 
ALTER TABLE 'supersearch_index_item' DROP KEY 'FullText';
Upgrade step 4 of 5... 
ALTER TABLE 'supersearch_index_item' ADD  KEY 'FullText' ('search_words');
Upgrade step 5 of 5... 
ALTER TABLE 'ticket_nachricht' ADD  KEY 'FullText' ('betreff','verfasser','text');
PHP Fatal error:  Uncaught mysqli_sql_exception: Specified key was too long; max key length is 3072 bytes in /var/www/html/OpenXE/upgrade/data/upgrade.php:423
Stack trace:
#0 /var/www/html/OpenXE/upgrade/data/upgrade.php(423): mysqli_query()
#1 /var/www/html/OpenXE/upgrade/data/upgrade.php(130): upgrade_main()
#2 {main}
  thrown in /var/www/html/OpenXE/upgrade/data/upgrade.php on line 421

```

**Comment by OpenXE-ERP** [comment]
Zieh mal bitte Upgrade und gib mir Rückmeldung ob es geklappt hat.

https://github.com/OpenXE-org/OpenXE/commit/623b041a5fa774fe6ed0aa43dde03a642d03dc01

**Comment by Diralytic** [comment]
Perfekt, funktioniert einwandfrei. Besten Dank!
